console.log("Irfan Saeed")
let myDate= new Date()
console.log(myDate)
console.log(myDate.toString())
console.log(myDate.toDateString())
console.log(myDate.toISOString())
console.log(myDate.toJSON())
console.log(myDate.toLocaleDateString())
console.log(myDate.toLocaleTimeString())
let mynewDate= new Date(2024,3,13)
console.log(mynewDate)
console.log(mynewDate.toLocaleString())
console.log(Math.floor(Date.now()/1000))
console.log(Math.floor(mynewDate.getTime()/1000))
